# Generated by Django 4.1.5 on 2023-01-10 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0012_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='marca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(upload_to='productos')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoApp.items')),
            ],
        ),
    ]
