# Generated by Django 4.1.5 on 2023-01-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0014_marca_remove_items_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='marca',
            new_name='name',
        ),
        migrations.AddField(
            model_name='items',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='productoApp.marca'),
        ),
    ]
