# Generated by Django 4.1.5 on 2023-01-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0016_rename_imag_imagenproducto_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='imag',
        ),
    ]
