# Generated by Django 4.1.5 on 2023-01-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0018_items_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='name',
            new_name='marca',
        ),
    ]
