# Generated by Django 4.1.5 on 2023-01-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0020_rename_nametag_tag_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
